Repository ansible-community/molecule-vagrant, pull requests merged in 2020-10, with the labels that each got.

#49 Avoid unportable /bin/true
  molecule_vagrant/test/scenarios/molecule/config_options/molecule.yml
  molecule_vagrant/test/scenarios/molecule/provider_config_options/molecule.yml
  molecule_vagrant/test/scenarios/molecule/vagrant_root/molecule.yml
Labels: bug

#44 Enable qemu fallback
  molecule_vagrant/test/functional/test_func.py
  molecule_vagrant/test/scenarios/molecule/config_options/molecule.yml
  molecule_vagrant/test/scenarios/molecule/provider_config_options/molecule.yml
  molecule_vagrant/test/scenarios/molecule/vagrant_root/molecule.yml
  tools/Vagrantfile
  tools/test-setup.sh
  tox.ini
Labels: feature

#52 Remove molecule filters
  molecule_vagrant/playbooks/create.yml
  molecule_vagrant/playbooks/destroy.yml
Labels: major

#55 Workaround for pip failure to perform editable install
  setup.py
Labels: bug

#54 Implement sanity checks for vagrant module
  molecule_vagrant/driver.py
Labels: feature

#58 Avoid depending on molecule.config
  molecule_vagrant/modules/vagrant.py
Labels: bug

#57 Enable github action integration
  .github/workflows/tox.yml
Labels: enhancement

#56 Make centos-8 zuul job voting
  zuul.d/layout.yaml
Labels: skip-changelog, test

#59 Disabled pytest capture
  tox.ini
Labels: skip-changelog, test

#60 Remove zuul pypi template
  zuul.d/layout.yaml
Labels: skip-changelog, test

#61 zuul: make jobs voting
  zuul.d/layout.yaml
Labels: skip-changelog, test

#64 Allow linked_cloned to be disabled
  molecule_vagrant/modules/vagrant.py
  molecule_vagrant/test/scenarios/molecule/default/molecule.yml
Labels: bug

#65 Switch testing nic to e1000
  molecule_vagrant/test/scenarios/molecule/provider_config_options/molecule.yml
  molecule_vagrant/test/scenarios/molecule/provider_config_options/verify.yml
Labels: skip-changelog, test

#67 Document Vagrant being unsupported on CentOS 8
  README.rst
  zuul.d/layout.yaml
Labels: major

#70 Added missing toml for build stage
  setup.cfg
Labels: bug

#72 Make driver compatible with molecule 3.2
  molecule_vagrant/test/functional/test_func.py
  setup.cfg
Labels: feature, major

#74 Consolidate devel testing
  .github/workflows/tox.yml
  setup.cfg
  tox.ini
Labels: skip-changelog, test

#76 Lint driver playbooks
  .pre-commit-config.yaml
  molecule_vagrant/playbooks/create.yml
  molecule_vagrant/playbooks/destroy.yml
Labels: bug

#78 Drop ansible as a direct dependency
  .pre-commit-config.yaml
  molecule_vagrant/driver.py
  setup.cfg
  tox.ini
Labels: enhancement

#79 Restore release pipeline
  .github/workflows/tox.yml
Labels: skip-changelog
