Repository ansible-community/molecule-vagrant, pull requests merged in 2020-05, with the labels that each got.

#21 zuul.d/layout.yaml: Remove python 2.7 centos 7 tests
  zuul.d/layout.yaml
Labels: gate

#22 Fix vagrant working directory
  molecule_vagrant/modules/vagrant.py
  molecule_vagrant/test/functional/test_func.py
  molecule_vagrant/test/scenarios/molecule/vagrant_root/converge.yml
  molecule_vagrant/test/scenarios/molecule/vagrant_root/molecule.yml
  molecule_vagrant/test/scenarios/molecule/vagrant_root/verify.yml
Labels: bug, gate

#16 allowing merge_dict calls to correctly update the main dict
  molecule_vagrant/modules/vagrant.py
Labels: bug, gate

#26 Fix linters config
  .pre-commit-config.yaml
Labels: gate

#28 Add documentation
  README.rst
Labels: docs, gate

#30 Testsuite devel fixes
  tools/test-setup.sh
  tox.ini
Labels: gate

#23 Add tests for config_options and provider_options
  molecule_vagrant/test/functional/test_func.py
  molecule_vagrant/test/scenarios/molecule/config_options/converge.yml
  molecule_vagrant/test/scenarios/molecule/config_options/molecule.yml
  molecule_vagrant/test/scenarios/molecule/config_options/verify.yml
  molecule_vagrant/test/scenarios/molecule/provider_config_options/converge.yml
  molecule_vagrant/test/scenarios/molecule/provider_config_options/molecule.yml
  molecule_vagrant/test/scenarios/molecule/provider_config_options/verify.yml
Labels: gate
