Repository ansible-community/molecule-vagrant, pull requests merged in 2021-11, with the labels that each got.

#133 Fix several CI failures
  .github/workflows/tox.yml
  .pre-commit-config.yaml
  molecule_vagrant/test/scenarios/molecule/network/molecule.yml
  molecule_vagrant/test/scenarios/molecule/provider_config_options/verify.yml
  tools/tox-py39/pre.yml
  zuul.d/layout.yaml
Labels: skip-changelog

#137 Avoid custom callback during testing
  tox.ini
Labels: skip-changelog

#136 Drop ansible extra dependency
  setup.cfg
  tox.ini
Labels: major

#139 Avoid using macos runners when not needed
  .github/workflows/tox.yml
Labels: skip-changelog

#140 Adopt shared GHA pipelines
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#138 Remove setup.py
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
Labels: major

#142 Chain GHA devel test runs
  .github/workflows/tox.yml
Labels: skip-changelog

#143 Add final check job
  .github/workflows/tox.yml
Labels: skip-changelog

#145 Minor fixes to tox config
  tox.ini
Labels: skip-changelog

#146 Enable vagrant box caching for GHA
  .github/workflows/tox.yml
Labels: skip-changelog

#147 Require molecule >= 3.4.1
  setup.cfg
Labels: bug

#148 Bump tox/pip used during testing
  tox.ini
Labels: skip-changelog

#149 tools/create_testbox.sh: Don't create test box if already available
  tools/create_testbox.sh
Labels: skip-changelog
