Repository ansible-community/molecule-vagrant, pull requests merged in 2021-07, with the labels that each got.

#122 Remove molecule pytest helpers
  molecule_vagrant/test/functional/test_func.py
Labels: bug

#124 Testbox memory
  tools/Vagrantfile
  tools/test-setup.sh
Labels: test

#121 Add code owners
  .github/CODEOWNERS
Labels: skip-changelog

#118 Spell out VirtualBox
  README.rst
  molecule_vagrant/playbooks/create.yml
  molecule_vagrant/playbooks/destroy.yml
Labels: docs

#120 Ensure jinja2 >= 2.11
  setup.cfg
Labels: bug
