Repository ansible-community/molecule-vagrant, pull requests merged in 2022-12, with the labels that each got.

#201 Update GH actions
  .github/workflows/release.yml
  .github/workflows/tox.yml
  requirements.txt
Labels: skip-changelog

#198 Update build-system requirements for setuptools-scm to >= 7.0.0
  pyproject.toml
Labels: bug

#188 Stop testing with ansible devel on py38
  .github/workflows/tox.yml
  tox.ini
Labels: bug

#202 Remove support for python 3.8
  .github/workflows/release.yml
  .github/workflows/tox.yml
  molecule_vagrant/playbooks/prepare.yml
  setup.cfg
  tox.ini
  zuul.d/layout.yaml
Labels: major

#203 Move pytest config to pyproject.toml
  conftest.py
  pyproject.toml
  pytest.ini
Labels: skip-changelog

#191 Silence ansible fqcn error about vagrant module.
  molecule_vagrant/playbooks/create.yml
  molecule_vagrant/playbooks/destroy.yml
  molecule_vagrant/test/scenarios/molecule/default-compat/create.yml
  molecule_vagrant/test/scenarios/molecule/default-compat/destroy.yml
Labels: bug

#206 use actions/setup-python@v4
  .github/workflows/tox.yml
Labels: skip-changelog
